@startuml "Поликлиника - классы"
left to right direction
class Товар{
    +Название: string
    +Тип товара: string
    +Артикул: integer
    +Срок хранения: datetime
    +Дата поступления: datetime
}
class Складовщик{
    +ФИО: string
    +Принять товара()
    +Списать товар()
    +Отправить товар получателю()
    +Отправить в место хранения()
}
Складовщик -- Товар: > манипуляции
@enduml