@startuml "Поликлиника диаграмма системы"
left to right direction
skinparam packageStyle rect
actor складовщик
rectangle Склад {
(поступление) -- складовщик
(место хранение) -- складовщик
(место хранение) <- (поступление)
складовщик -- (уход - продажа)
складовщик -- (списание)

}
@enduml