@startuml "Диаграмма развёртывания"
top to bottom direction
node Курьер{
        artifact "Доставщик"
        }
node Селлер{
       artifact "Перевозчик"
       }
node Товар{
}

node Складовщик{
    artifact "работник склада"
}
node Клиент{
    artifact "Получает товар"
    }
Селлер 0--0 Наклодная: прием товара
Наклодная 0--0 Складовщик: распределение на складе
node Наклодная{
node "Транспортная накладная" {
    artifact "Информация о поставке"
}
node "Акт приема передачи"{
}
}
Селлер --0 Складовщик: взаимодействие
Товар --0 Селлер
Складовщик --0 Курьер: передача товара на доставку
Курьер --0 Клиент: Получение товара
Клиент --0 Селлер: Заказ товара
@enduml