@startuml "Диаграмма последовательности"
participant Селлер
participant Наклодная
participant Складовщик
participant Курьер
participant Клиент

Клиент -> Селлер: 1. Заказ товара
Селлер -> Складовщик: 2. Доставка товара на склад
Наклодная -> Складовщик: 3. Распределение товара
Складовщик -> Курьер: 4. Передача товара
Курьер -> Клиент: 5. Доставка товара

@enduml